UI/Areas/Admin/Controllers/AddressController.cs
using BLL;
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class AddressController : BaseController
    {
        AddressBLL bll = new AddressBLL();
        // GET: Admin/Address
        public ActionResult AddAddress()
        {
            AddressDTO dto = new AddressDTO();
            return View(dto);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddAddress(AddressDTO model)
        {
            if (ModelState.IsValid)
            {
                if(bll.AddAddress(model))
                {
                    ViewBag.ProcessState = General.Messages.AddSuccess;
                    ModelState.Clear();
                    model = new AddressDTO();
                }
                else
                    ViewBag.ProcessState = General.Messages.GeneralError;
            }
            else
            {
                ViewBag.ProcessState = General.Messages.EmptyArea;
            }
            return View(model);
        }
    }
}

UI/Areas/Admin/Views/Address/AddAddress.cshtml
@{
    ViewBag.Title = "AddAddress";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">
    <h1>Add Address</h1>
    <ol class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Address</a></li>
        <li class="breadcrumb-item active"><a>Add Address</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/Address/AddressList'">Address List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("AddAddress", "Address", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/AddressForm")
                }

            </div>
        </div>
    </div>
</section>